name: Test API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: 'Create env file'
        run: |
          touch .env
          echo WL_CLIENT_ID="${{ secrets.WL_CLIENT_ID }}" >> .env
          echo WL_CLIENT_SECRET="${{ secrets.WL_CLIENT_SECRET }}" >> .env
          echo WL_BEARER="${{ secrets.WL_BEARER }}" >> .env
          cat .env
      - name: 'Testing NPM'
        run: |
          npm ci
          npm test
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
      - name: Create release
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
      - name: Create Release
        id: create_release
        if: steps.check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PERSONNAL }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.check.outputs.version }}
          release_name: Release ${{ steps.check.outputs.version }}
          body: |
            **Full Changelog**: https://github.com/K0bus/warcraftlog-api-v2/commits/${{ steps.check.outputs.version }}
          draft: false
          prerelease: true